# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  #vmImage: windows-latest
  name: 'SelfHostedPool'

jobs:
  - job: Regression_NewTestCases
    displayName: "Regression(New) testcase execution"
    steps:
      - task: Maven@4
        inputs:

          mavenPomFile: 'pom.xml'
          goals: 'test'
          options: >
            -DsuiteXmlFile=testng-suites/NewTestCasesSuite.xml 
            -DexcludedGroups=flaky
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'Automation Enginner (SDET)- Vaibhav Chavan'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          checkStyleRunAnalysis: true
          pmdRunAnalysis: true
          findBugsRunAnalysis: true

      - task: CopyFiles@2
        displayName: 'Copy ExtentReports + Linked Assets'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
            reports/**
            screenshots/**
            logs/**
          TargetFolder: '$(Build.ArtifactStagingDirectory)/ExtentReportBundle'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish ExtentReports Artifact with Assets'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/ExtentReportBundle'
          ArtifactName: 'ExtentReport'
          publishLocation: 'Container'