name: Regression Test Execution

on:
  push:
    branches:
      - master

jobs:
  regression-test:
    name: Regression Testcase Execution
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Run Tests
        run: mvn test -DsuiteXmlFile=testng-suites/NewTestCasesSuite.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/surefire-reports/TEST-*.xml'

      - name: Upload Target Folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: target
