name: Java CI

on:
  push:
    branches:
      - main  # Trigger the CI when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger CI on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (or any other version)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run tests
      - name: Run tests
        run: mvn test
