name: Maven Regression Tests

on:
  workflow_dispatch:   # Manual trigger only

jobs:
  regression-test:
    runs-on: windows-latest
    timeout-minutes: 120
    name: Nightly Regression Suite

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Run Maven tests
      - name: Run Maven Tests
        run: mvn -DsuiteXmlFile="testng-suites/RegressionTestSuite.xml" -DexcludedGroups=flaky test

      # Upload JUnit results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: '**/surefire-reports/TEST-*.xml'

      # Copy ExtentReports + assets (PowerShell version for Windows)
      - name: Archive ExtentReports + Assets
        run: |
          New-Item -ItemType Directory -Force -Path ExtentReportBundle
          if (Test-Path reports) { Copy-Item reports -Destination ExtentReportBundle -Recurse }
          if (Test-Path screenshots) { Copy-Item screenshots -Destination ExtentReportBundle -Recurse }
          if (Test-Path logs) { Copy-Item logs -Destination ExtentReportBundle -Recurse }
        shell: pwsh

      # Publish ExtentReports as Artifact
      - name: Upload ExtentReport
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: ExtentReportBundle